### ISSUE TITLE
Wakeword/playback not working

### ISSUE THREAD

**Issue by ChrisB85** [poulsp/docker-Alice-Linux-x86#1]
Hi!
Currently I'm using Snips using docker (my own build https://github.com/ChrisB85/snips_docker), but it's time to move forward since Snips is closed project. I tried to run Project Alice using your docker images and everything seems to be installed correctly, but after running Alice, MQTT server and saying "Hey Snips/Hey Alice" nothing happens. I'm not sure if audio is set up correctly. Running ```arecord -t wav -Dhw:0 -f S16_LE -c 2 -r 16000 out.wav``` in Alice container records sound, playback also works. In log I see ```Scheduled next random speaking in X seconds```, but i don't hear anything. ```snips-watch``` also does not show anything except ```Watching on 172.18.0.3:1883 (MQTT)```

Can you give me any suggestions how to deal with that? Thanks in advance!

**Comment by poulsp** [comment]
Hi @ChrisB85, don,t use the internal mosquitto broker but the included mosquitto docker or you own mosquitto broker and set the mqtthost to that IP. for the included mosquitto docker it's your host's IP.


The project is update for 6 days ago Thu Oct 8.

Are you at ProjectAlice discord?

`https://discord.gg/C6HNtzV`

Update: if you use the internal mosquitto broker set it to your Host IP.

**Comment by ChrisB85** [comment]
OK, so here is what I did:
1. I have configured everything once again and now I'm sure that MQTT server (I'm using one from your repo) is set up correctly with Alice. I'm able to connect to it from another PC using MQTT Explorer, I see some messages (including hermes/audioServer/*).
2. After entering AWS credentials into config file I see that audio cache files are created and I can play them from container shell using `aplay`.
3. I have set up alice/Docker/host_volumes/config/asound.conf (I think that step is missing in your installation guide):

```
pcm.!default {
   type asym
   capture.pcm "aliceMic"
   playback.pcm "aliceSpeaker"
}

pcm.aliceMic {
   type plug
   slave {
      pcm "hw:0,0"
   }
}
   
pcm.aliceSpeaker {
   type plug
   slave {
      pcm "hw:0,0"
   }
}
```
basing on:
```
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: 92HD95 Analog [92HD95 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
```
arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: 92HD95 Analog [92HD95 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

but still - wake word is not detected and I can't hear anything that Alice says on my laptop.
BUT the funny thing is that I was able to successfully connect my Snips satellite and I can talk with Alice through it!

Do you have any suggestions why Alice audio is not working on my host and what I can check?

**Comment by poulsp** [comment]
Have you set `"disableSoundAndMic": false` in config.json?
Can you display here the  alice/Docker/host_volumes/config/snips.toml.

**Comment by ChrisB85** [comment]
BINGO! I didn't noticed that option earlier :) Thanks!
