### ISSUE TITLE
Please forgive me ;-)

### ISSUE THREAD

**Issue by wraithrmm** [poulsp/docker-Alice-Linux-x86#2]
Sorry for contacting you this way, but I could not find another way to do so, but I wanted to run Alice in a docker on my Raspbery PI, which I have now done here:

https://github.com/wraithrmm/project-alice-docker

But I wanted to see if there was a way we could collaborate to get one centralised solution for docker and alice?

My solution offers some scripts for setting the config.json settings using environment variables you might be interested in and also I have attempted to do as little manual/static dependancy management in my docker file as possible, leaving Alice to install as much as she can, which is a little more future proof.

Mine is still an early prototype and while it does lead to an docker that has alice responding to my satellites, it requires allot more work yet and none of the project data files are mapped to volumes yet, which I want to add.

I plane to may the ProjectAlice directory eventually, but again, I wanted this installed into the image to allow dependancies to be installed by alice during build.

Anyway, let me know if you wanna collaborate :-) It would be good to have just one solution that worked for Ubuntu and PI, simply be switching the base OS but then leaving everything else the same :-)

Oh, also, I pinched your systemctl file as a quick solution for that, so would like to credit for that of course if we don't end up just merging our two approaches :-)

**Comment by poulsp** [comment]
Hi, @wraithrmm
It's an interesting project you do there.
Are you at ProjectAlice discord?
`https://discord.gg/C6HNtzV`
It's easyer to talk there.
